### ISSUE TITLE
  **ERROR** A multi-buildpack.yml file must be provided at your app root to use this buildpack.

### ISSUE THREAD

**Issue by iftekharkhan09** [cloudfoundry/multi-buildpack#7]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

CF verison - 6.34.0+f53d03a5e.2018-01-09

What version of the buildpack you are using?

  - https://github.com/cloudfoundry/python-buildpack
  - https://github.com/cloudfoundry/java-buildpack

If you were attempting to accomplish a task, what was it you were attempting to do?

I am trying to include the buildpack for both python and Java in my application

What did you expect to happen?

I expect it to find the 2 buildpacks that i have given in the file - 'multi-buildpack.yml' and include this 2 buildpacks in the predix platform that uses cloud foundry.

What was the actual behavior?

I am getting the below error:-
  **ERROR** A multi-buildpack.yml file must be provided at your app root to use this buildpack.

Please confirm where necessary:
* [x] I have included a log output  
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by sclevine** [comment]
You would need to put `multi-buildpack.yml` inside of the JAR file to use Java as the final buildpack. Alternatively, you could unzip the JAR file, place the `multi-buildpack.yml` file inside the resulting directory, and push from inside of that directory.

Note that this is only a limitation of the multi-buildpack buildpack, as it is a temporary, shim buildpack. All recently released versions of Cloud Foundry natively support multi-buildpack mode.

**Comment by sclevine** [comment]
Closing as addressed.
